# Important readings
# https://docs.docker.com/compose/networking/

version: '3'
services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '5000:3000'
    volumes:
      - grafana_data:/var/lib/grafan
    networks:
      - backend
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - '8787:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tiwyw.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend
    depends_on:
      - postgres

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    container_name: minio
    env_file:
      - .env.docker
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - minio_data:/data
    networks:
      - backend
    ports:
      - 9000:9000
      - 9001:9001

networks:
  backend:
    driver: bridge

volumes:
  grafana_data:
  postgres_data:
  pgadmin_data:
  minio_data:
